const {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  ShadingType,
} = require("docx");

function cleanText(value) {
  if (!value) return "";

  return String(value)
    .replace(/\r/g, "")
    .replace(/\*\*/g, "")
    .replace(/\*/g, "")
    .replace(/#{1,6}\s?/g, "")
    .replace(/`/g, "")
    .replace(/_{2,}/g, "")
    .replace(/-{3,}/g, "")
    .replace(/\[|\]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function tableBorders() {
  return {
    top: { style: BorderStyle.SINGLE, size: 1, color: "BFBFBF" },
    bottom: { style: BorderStyle.SINGLE, size: 1, color: "BFBFBF" },
    left: { style: BorderStyle.SINGLE, size: 1, color: "BFBFBF" },
    right: { style: BorderStyle.SINGLE, size: 1, color: "BFBFBF" },
  };
}

function createParagraph(text, options = {}) {
  return new Paragraph({
    spacing: {
      after: options.after ?? 140,
      before: options.before ?? 0,
      line: 276,
    },
    alignment: options.alignment || AlignmentType.LEFT,
    children: [
      new TextRun({
        text: cleanText(text),
        bold: options.bold || false,
        italics: options.italics || false,
        size: options.size || 22,
        color: options.color || "1F1F1F",
      }),
    ],
  });
}

function createMainHeading(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: {
      before: 300,
      after: 160,
    },
    border: {
      bottom: {
        color: "5F2C82",
        space: 6,
        style: BorderStyle.SINGLE,
        size: 8,
      },
    },
    children: [
      new TextRun({
        text: cleanText(text).toUpperCase(),
        bold: true,
        size: 28,
        color: "5F2C82",
      }),
    ],
  });
}

function createBullet(text) {
  return new Paragraph({
    bullet: {
      level: 0,
    },
    spacing: {
      after: 100,
      line: 276,
    },
    children: [
      new TextRun({
        text: cleanText(text),
        size: 22,
        color: "1F1F1F",
      }),
    ],
  });
}

function createInfoTable(talk) {
  const workAreas =
    talk.targetWorkAreas && talk.targetWorkAreas.length > 0
      ? talk.targetWorkAreas.map((wa) => wa.name).join(", ")
      : "N/A";

  const rows = [
    ["Talk Number", talk.talkNumber ? `#${talk.talkNumber}` : "N/A"],
    ["Title", talk.title || "N/A"],
    ["Target Work Area(s)", workAreas],
    ["Duration", `${talk.duration || 5} minutes`],
    [
      "Date",
      talk.date ? new Date(talk.date).toLocaleDateString("en-GB") : "N/A",
    ],
    ["Generated By", talk.generatedBy?.name || "N/A"],
    ["Conducted By", talk.conductedBy?.name || "N/A"],
    ["Status", talk.status || "N/A"],
  ];

  return new Table({
    width: {
      size: 100,
      type: WidthType.PERCENTAGE,
    },
    rows: rows.map(
      ([label, value]) =>
        new TableRow({
          children: [
            new TableCell({
              width: {
                size: 32,
                type: WidthType.PERCENTAGE,
              },
              shading: {
                type: ShadingType.CLEAR,
                fill: "E8DFF5",
              },
              borders: tableBorders(),
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: label,
                      bold: true,
                      size: 22,
                      color: "5F2C82",
                    }),
                  ],
                }),
              ],
            }),
            new TableCell({
              width: {
                size: 68,
                type: WidthType.PERCENTAGE,
              },
              borders: tableBorders(),
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: cleanText(value),
                      size: 22,
                      color: "1F1F1F",
                    }),
                  ],
                }),
              ],
            }),
          ],
        }),
    ),
  });
}

function createTopicsSection(talk) {
  const children = [];

  if (!talk.topics || talk.topics.length === 0) {
    children.push(createParagraph("No topics recorded.", { italics: true }));
    return children;
  }

  talk.topics.forEach((topic) => {
    children.push(createBullet(topic));
  });

  return children;
}

function createAttendanceSection(talk) {
  const children = [];

  children.push(createMainHeading("Attendance Record"));

  children.push(
    createParagraph(
      "Use this section during or after the safety talk to record attendance and confirm worker participation.",
    ),
  );

  const rows = [
    new TableRow({
      children: ["No.", "Name", "Role / Department", "Signature"].map(
        (heading) =>
          new TableCell({
            shading: {
              type: ShadingType.CLEAR,
              fill: "E8DFF5",
            },
            borders: tableBorders(),
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: heading,
                    bold: true,
                    color: "5F2C82",
                    size: 22,
                  }),
                ],
              }),
            ],
          }),
      ),
    }),
  ];

  const attendeeCount = Math.max(talk.attendance?.totalAttendees || 10, 10);

  for (let i = 1; i <= attendeeCount; i++) {
    rows.push(
      new TableRow({
        children: [String(i), "", "", ""].map(
          (value) =>
            new TableCell({
              borders: tableBorders(),
              children: [
                new Paragraph({
                  spacing: { after: 120 },
                  children: [
                    new TextRun({
                      text: value,
                      size: 22,
                    }),
                  ],
                }),
              ],
            }),
        ),
      }),
    );
  }

  children.push(
    new Table({
      width: {
        size: 100,
        type: WidthType.PERCENTAGE,
      },
      rows,
    }),
  );

  return children;
}

function createSignOffSection() {
  return [
    createMainHeading("Facilitator Sign-Off"),

    createParagraph(
      "The person conducting the safety talk should sign below after the talk has been delivered and attendance has been recorded.",
    ),

    new Table({
      width: {
        size: 100,
        type: WidthType.PERCENTAGE,
      },
      rows: [
        new TableRow({
          children: [
            new TableCell({
              borders: tableBorders(),
              children: [
                createParagraph("Conducted By:", {
                  bold: true,
                  color: "5F2C82",
                }),
                createParagraph("Name: ______________________________"),
                createParagraph("Signature: ___________________________"),
                createParagraph("Date: _______________________________"),
              ],
            }),
            new TableCell({
              borders: tableBorders(),
              children: [
                createParagraph("Reviewed By:", {
                  bold: true,
                  color: "5F2C82",
                }),
                createParagraph("Name: ______________________________"),
                createParagraph("Signature: ___________________________"),
                createParagraph("Date: _______________________________"),
              ],
            }),
          ],
        }),
      ],
    }),
  ];
}

async function generateSafetyTalkWordBuffer({ talk }) {
  const children = [];

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: {
        after: 300,
      },
      children: [
        new TextRun({
          text: "SAFETY TALK / TOOLBOX TALK",
          bold: true,
          size: 38,
          color: "5F2C82",
        }),
      ],
    }),
  );

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: {
        after: 400,
      },
      children: [
        new TextRun({
          text: cleanText(talk.title || "Safety Talk"),
          bold: true,
          size: 28,
          color: "2F5597",
        }),
      ],
    }),
  );

  children.push(createInfoTable(talk));

  children.push(
    createParagraph(
      "This editable Word document was generated from the safety talk record. The Safety Officer or facilitator may edit it, print it, use it during the toolbox talk, record attendance, sign it, and file it as evidence of communication.",
      {
        before: 300,
        italics: true,
        color: "666666",
      },
    ),
  );

  if (talk.sections?.opening) {
    children.push(createMainHeading("Opening Statement"));
    children.push(createParagraph(talk.sections.opening));
  }

  if (talk.sections?.mainPoints && talk.sections.mainPoints.length > 0) {
    children.push(createMainHeading("Main Safety Points"));
    talk.sections.mainPoints.forEach((point) => {
      children.push(createBullet(point));
    });
  }

  if (
    talk.sections?.discussionQuestions &&
    talk.sections.discussionQuestions.length > 0
  ) {
    children.push(createMainHeading("Discussion Questions"));
    talk.sections.discussionQuestions.forEach((question) => {
      children.push(createBullet(question));
    });
  }

  if (talk.sections?.keyTakeaways && talk.sections.keyTakeaways.length > 0) {
    children.push(createMainHeading("Key Takeaways"));
    talk.sections.keyTakeaways.forEach((takeaway) => {
      children.push(createBullet(takeaway));
    });
  }

  if (talk.sections?.closing) {
    children.push(createMainHeading("Closing Reminder"));
    children.push(createParagraph(talk.sections.closing));
  }

  if (
    !talk.sections?.opening &&
    !talk.sections?.mainPoints?.length &&
    talk.content
  ) {
    children.push(createMainHeading("Safety Talk Content"));

    const lines = String(talk.content)
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean);

    lines.forEach((line) => {
      if (/^[-*•]\s+/.test(line)) {
        children.push(createBullet(line.replace(/^[-*•]\s+/, "")));
      } else if (/^\d+\.\s+/.test(line)) {
        children.push(createParagraph(line));
      } else if (/^#{1,6}\s+/.test(line)) {
        children.push(createMainHeading(line.replace(/^#{1,6}\s+/, "")));
      } else {
        children.push(createParagraph(line));
      }
    });
  }

  children.push(createMainHeading("Topics Covered"));
  children.push(...createTopicsSection(talk));

  children.push(...createAttendanceSection(talk));
  children.push(...createSignOffSection());

  const doc = new Document({
    creator: "TrueSafe Safety Talk System",
    title: cleanText(talk.title || "Safety Talk"),
    description: "Editable Safety Talk Word document",
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1000,
              right: 900,
              bottom: 1000,
              left: 900,
            },
          },
        },
        children,
      },
    ],
  });

  return await Packer.toBuffer(doc);
}

module.exports = {
  generateSafetyTalkWordBuffer,
};
